set_property PACKAGE_PIN V17 [get_ports href]
set_property PACKAGE_PIN V16 [get_ports ref2]
set_property PACKAGE_PIN W16 [get_ports ref3]
set_property PACKAGE_PIN W17 [get_ports ref4]
set_property PACKAGE_PIN U16 [get_ports vote]

set_property IOSTANDARD LVCMOS33 [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports ref2]
set_property IOSTANDARD LVCMOS33 [get_ports ref3]
set_property IOSTANDARD LVCMOS33 [get_ports ref4]
set_property IOSTANDARD LVCMOS33 [get_ports vote]
